spring:
  application:
    name: WELCOME-SERVICE
  boot:
    admin:
      client:
        url: http://localhost:2222/
#server:
#  port : 3333
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

