spring:
  application:
    name: APIGateway-SERVICE
  cloud:
    gateway:
      routes:
        - id: api-1
          uri:  lb://WELCOME-SERVICE
          predicates:
            - Path=/welcome/**
        - id: api-2
          uri:  lb://GREETING-SERVICE
          predicates:
            - Path=/greet/**
server:
  port : 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
